-- Vintage 337 — core schema (PostgreSQL / Supabase)
-- Aligns with JPA entities under com.vintage337.entity

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(120) NULL,
  role VARCHAR(32) NOT NULL DEFAULT 'CUSTOMER',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL,
  CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  category VARCHAR(120) NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  stock INT NOT NULL DEFAULT 0,
  description TEXT NULL,
  image_url VARCHAR(2048) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL
);

CREATE INDEX idx_products_category ON products (category);
CREATE INDEX idx_products_active ON products (active);

CREATE TABLE customer_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number VARCHAR(32) NOT NULL,
  user_id BIGINT NULL,
  customer_email VARCHAR(255) NULL,
  customer_name VARCHAR(200) NULL,
  status VARCHAR(32) NOT NULL,
  total_amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL,
  CONSTRAINT uk_customer_orders_number UNIQUE (order_number),
  CONSTRAINT fk_customer_orders_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_customer_orders_user ON customer_orders (user_id);
CREATE INDEX idx_customer_orders_status ON customer_orders (status);

CREATE TABLE customer_order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  quantity INT NOT NULL,
  unit_price DECIMAL(10, 2) NOT NULL,
  CONSTRAINT fk_customer_order_items_order FOREIGN KEY (order_id) REFERENCES customer_orders (id) ON DELETE CASCADE,
  CONSTRAINT fk_customer_order_items_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE INDEX idx_customer_order_items_order ON customer_order_items (order_id);
CREATE INDEX idx_customer_order_items_product ON customer_order_items (product_id);
